import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      {/* Include shared UI here e.g. a header or sidebar */}
      <nav className="bg-gray-800 p-4">
        <div className="flex items-center justify-between">
          <Link href="/" className="text-white text-lg font-semibold">
            Home
          </Link>
          <div>
            <Link
              href="/createResume"
              className="text-white text-lg font-semibold mr-4"
            >
              Create Resume
            </Link>
          </div>
          <div>
            <Link
              href="/createEducation"
              className="text-white text-lg font-semibold mr-4"
            >
              Create Education
            </Link>
          </div>
          <div>
            <Link
              href="/addEducation"
              className="text-white text-lg font-semibold mr-4"
            >
              Add Education
            </Link>
          </div>
          <div>
            <Link
              href="/createEmployment"
              className="text-white text-lg font-semibold mr-4"
            >
              Create Employment
            </Link>
          </div>
          <div>
            <Link
              href="/addEmployment"
              className="text-white text-lg font-semibold mr-4"
            >
              Add Employment
            </Link>
          </div>
          <div>
            <Link
              href="/createActivity"
              className="text-white text-lg font-semibold mr-4"
            >
              Create Activity
            </Link>
          </div>
          <div>
            <Link
              href="/addActivity"
              className="text-white text-lg font-semibold mr-4"
            >
              Add Activity
            </Link>
          </div>
        </div>
      </nav>
      {children}
    </section>
  );
}
